[book]
title = "AFS Tutorial"
author = "Roshan, Grace, and Shreya"
description = "A resource for learning AFS"

[build]
build-dir = "docs/"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = []
mathjax-support = true

[output.html.search]
limit-results = 15

